apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-app-gcp
  namespace: default
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: flask-app-gcp-active
      previewService: flask-app-gcp-preview
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: flask-app-gcp
  template:
    metadata:
      labels:
        app: flask-app-gcp
    spec:
      containers:
        - name: flask-app
          image:  ${IMAGE_URI}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: flask-app-env-gcp
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
 