apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-secret" .Release.Name }}
  namespace: default
  labels:
    app.kubernetes.io/name: {{ include "flask-app.name" . }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "flask-app.chart" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}
  secret: {{ .Values.secret | quote }}
