apiVersion: v1
kind: Secret
metadata:
  name: flask-app-db-secret
  namespace: default
type: Opaque
data:
  username: {{ .Values.db.user | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}
