replicaCount: 2

service:
  type: ClusterIP

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 600m
    memory: 600Mi

ingress:
  enabled: true
  host: refonte-flask-app.devopsguru.today # replace with your GoDaddy domain
  annotations:
    kubernetes.io/ingress.class: gce

db:
  host: refonte-flask-db.devopsguru.today # replace with your GoDaddy
  port: { { .Values.db.port } }
  name: { { .Values.db.name } }
  user: { { .Values.db.user } }
  password: { { .Values.db.password } }
