replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: flask-app.devopsguru.today
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb

env:
  # Database credentials are pulled from Kubernetes Secret
  secretName: flask-app-db-secret
  FLASK_ENV: production

db:
  host: "terraform-20251023140416272500000006.cjjbcu9s6nug.us-east-1.rds.amazonaws.com"  
  port: 5432
  name: "postgresdb"
  user: "postgres"
  password: ""
