replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd:latest
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: flask-app.devopsguru.today
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing

env:
  # Database credentials are pulled from Kubernetes Secret
  secretName: { { .Values.env.secretName } }
