replicaCount: 2

service:
  type: ClusterIP

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 600m
    memory: 600Mi

ingress:
  enabled: true
  host: flask-app.gcp.example.com
  annotations:
    kubernetes.io/ingress.class: gce
