replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80           # external LoadBalancer port
  targetPort: 8080   # container port (Flask listens here)

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

env:
  # Loaded from Kubernetes Secret
  secretName: flask-app-db-secret-aws
  FLASK_ENV: production

db:
  awsHost: "terraform-20251029131648903600000006.cjjbcu9s6nug.us-east-1.rds.amazonaws.com"
  awsName: "postgresdb"
  awsUsername: "postgres"
  awsPassword: "AWS_DB_PASSWORD" # Will be filled dynamically from .env or Secret
   
   

ingress:
  enabled: true
  ingressClassName: alb
  host: aws.flask-app.devopsguru.today
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

secret: "SECRET_KEY" # Will be filled dynamically from .env or Secret
 