replicaCount: 2

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: "refonte-flask-app.devopsguru.today"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing

db:
  secretName: "flask-db-secret" # must exist in AWS cluster
