replicaCount: 2

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 600m
    memory: 600Mi

ingress:
  enabled: true
  host: "refonte-flask-app.devopsguru.today"
  annotations:
    kubernetes.io/ingress.class: gce

db:
  secretName: "flask-db-secret"
