replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

env:
  secretName: flask-app-db-secret-gcp
  FLASK_ENV: production

db:
  gcpHost: "34.132.219.169"
  gcpName: "postgresdb"
  gcpUsername: "postgres"
  gcpPassword: "GCP_DB_PASSWORD"          # will be dynamically injected from .env via deploy.sh

ingress:
  enabled: true
  ingressClassName: gce
  host: gcp.flask-app.devopsguru.today
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: flask-app-ip 

secret: "SECRET_KEY"
 