replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000   # containerPort inside the pod (Flask listens here)

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 600m
    memory: 600Mi

ingress:
  enabled: true
  host: gcp.flask-app.devopsguru.today
  ingressClassName: gce
  annotations:
    kubernetes.io/ingress.class: "gce"

env:
  # Database credentials are pulled from Kubernetes Secret
  secretName: flask-app-db-secret
  FLASK_ENV: production

db:
  host: "34.60.111.42"
  port: 5432
  name: "postgresdb"
  user: "postgres"
  password: ""

secret: ""
 