replicaCount: 2

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: "refonte-flask-app.devopsguru.today"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "refonte-flask-app.devopsguru.today"

db:
  secretName: "flask-db-secret"
  host: "${DB_HOST}"
  port: "5432"
  name: "flaskdb"
  user: "flask_user"
  password: "flask_password"
