replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80           # external LoadBalancer port
  targetPort: 5000   # containerPort inside the pod (Flask listens here)

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: aws.flask-app.devopsguru.today
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    kubernetes.io/ingress.class: "alb"
  
env:
  # Database credentials are pulled from Kubernetes Secret
  secretName: flask-app-db-secret
  FLASK_ENV: production

db:
  host: "" 
  port: 5432
  name: ""
  user: ""
  password: ""

secret: ""
