replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: flask-app.devopsguru.today
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing

env:
  # Database credentials are pulled from Kubernetes Secret
  secretName: flask-app-db-secret

db:
  host: "terraform-20251021132428313100000006.cjjbcu9s6nug.us-east-1.rds.amazonaws.com"
  port: 5432
  name: "postgresdb"
  user: "postgres"
  password: ""
