replicaCount: 2

image:
  repository: kmkouokam/flaskr-tdd
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type:  LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 600m
    memory: 600Mi

ingress:
  enabled: true
  ingressClassName: gce
  host: flask-app.devopsguru.today
  annotations:
    kubernetes.io/ingress.class: gce

env:
  # Database credentials are pulled from Kubernetes Secret
  secretName: flask-app-db-secret
  FLASK_ENV: production

db:
  host: "136.112.4.195"
  port: 5432
  name: "postgresdb"
  user: "postgres"
  password: ""
