replicaCount: 2

service:
  type: LoadBalancer

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  host: refonte-flask-app.devopsguru.today # replace with your GoDaddy domain
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
